Rename the project name to `connect`
Ilhasoft/weni-engine pull request #54
Opened 2021-09-23 21:34 UTC by Sandro-Meireles

The name of the project(`weni`) was conflicting with `weni-protobuffers` package namespace, this PR aims to solve this problem by changing the name of the project to `connect`. 

The `weni-protobuffers` package was added to the project,  and all imports from `weni.protos` have been changed to follow the package patterns.

2021-09-23 21:45 UTC, jcbalmeida approved these changes

2021-09-23 21:46 UTC, jcbalmeida requested changes
You need to change .corevagerc too

2021-09-23 22:20 UTC, jcbalmeida approved these changes

2021-09-28 19:02 UTC, helllllllder reviewed
Só uma dúvida, pq o PR ta indo direto para a Main? ja foi testado em dev e em staging?

2021-09-28 19:05 UTC, helllllllder approved these changes

2021-09-28 19:06 UTC, helllllllder approved these changes

2021-09-28 19:24 UTC, matmsa27 commented
@Sandro-Meireles a observação do @helllllllder é muito importante, vai pra main mesmo? num é bom mudar pra dev primeiro não?

2021-10-30 00:41 UTC, AlisoSouza approved these changes

2021-10-30 02:35 UTC, merged